### ISSUE TITLE
draw documentation issue

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [image-js/image-js-typescript#109]
https://image-js.github.io/image-js-typescript/classes/IJS.html#drawPolygon

![image](https://user-images.githubusercontent.com/56769876/175098907-4c2ccecb-05c0-4080-917a-5a7af29dda02.png)

**Comment by opatiny** [comment]
Was the issue here that the comments were missing? If yes, that seems to be fixed, otherwise could you please elaborate? Thanks!

**Comment by wadjih-bencheikh18** [comment]
> the comments were missing?

yes, thank you
