### ISSUE TITLE
Calculations on Mask ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#113]
Should we calculate properties like mbr, ferret, filled, etc on Roi or on Mask ? I seems to me that it could be calculated directly on a mask and return a new mask. One problem I see is that the MBR could be larger than the current mask and therefore `mask.mbr()` need to return a mask with the position of the former origin.

The reason for those thoughts is that we have a method `roi.getMask()` but in some cases we would like to join rois to get a mask from the union.

We could think about `roiMapManager.getUnionMask(roiID[])` in this case.

**Comment by opatiny** [comment]
Since the `RoiMapManager` has access to all the ROIs, it seems to be a good idea to implement `getUnionMask()` on it imo. Indeed, we couldn't really implement it on `Roi` since we would have to call it as `roi.getUnionMask(otherRoiIds)` which is odd.

**Comment by opatiny** [comment]
Related issues:
- Generalities: #121
- MBR: #130 
- Feret diameters: #137
