### ISSUE TITLE
Bug with `drawPolygon`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#114]
Consider the following example:
```ts
    const image = new IJS(3, 3, { colorModel: ImageColorModel.GREY });
    const points = [
      { column: 0, row: 1 },
      { column: 1, row: 2 },
      { column: 2, row: 1 },
      { column: 1, row: 0 },
    ];

    const result = image.drawPolygon( points, {
      fillColor: [6],
      strokeColor: [3],
    });
    
    console.log(result);
```

Currently `result` is
```ts
result = [
      [0, 3, 0],
      [3, 0, 3],
      [0, 3, 0],
];
```
Whereas since the fill color is specified, I would expect:
```ts
result = [
      [0, 3, 0],
      [3, 6, 3],
      [0, 3, 0],
];
```

**Comment by opatiny** [comment]
I tried to look for an existing algorithm to detect wheter a point is inside a polygon. In `opencv`, the Ray casting algorithm is used: https://en.wikipedia.org/wiki/Point_in_polygon

**Comment by targos** [comment]
In legacy image-js, we used [robust-point-in-polygon](https://github.com/image-js/image-js/blob/675bafe1ec5f78d2d5d36df67e14e254d27a1f2d/src/image/roi/Roi.js#L2)

**Comment by opatiny** [comment]
Should I fix this bug using this library? It uses polygons defined as an array of points in the `[x,y]` format.

**Comment by targos** [comment]
> Should I fix this bug using this library?

What's the alternative?

> It uses polygons defined as an array of points in the [x,y] format.

If you have an array of objects, it should not be an issue to convert it before using the library.
