### ISSUE TITLE
Implement `getMbrMask`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#117]
Add a new kind `mbr` to `roi.getMask()` which returns the mask with the minimum bounding rectangle of the ROI.

**Comment by opatiny** [comment]
How should I manage the fact that the MBR can be larger than the original ROI (or in any case have different dimensions)?
Do I need a way to trace the MBR position in the original image and if yes, how could I make that @targos ?

**Comment by targos** [comment]
After discussion, this should be fixed by adding a new property `origin` to images (https://github.com/image-js/image-js-typescript/issues/121).
