### ISSUE TITLE
Image inspection should not print data for large images

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#127]
We potentially don't have enough time, memory and place in the terminal to see everything.

https://github.com/image-js/image-js-typescript/blob/24a123720f45e8a8219f995d23e4e70165d8f54a/src/IJS.ts#L412

**Comment by opatiny** [comment]
What would be the maximal image dimensions for which you'd like to have the data printed?

**Comment by targos** [comment]
I don't know. If there is no sensible limit, I'm okay with just never printing the data.

**Comment by opatiny** [comment]
For debugging seeing the data is very practical. I would set an arbitrary limit around 20x20 pixels, so that I can still see the data for small images.
