### ISSUE TITLE
Bug with `drawLine`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#129]
I use `drawRectangle` to display the minimum bounding rectangle of an ROI and I noticed that in some cases the sides of the rectangle are not complete, as shown in the image below.
![image](https://user-images.githubusercontent.com/17711389/178291781-774ce216-62af-4ada-90b4-74d577510e71.png)

**Comment by targos** [comment]
Are you sure it's `drawRectangle` ? This method can only draw straight rectangles and it is tilted in your screenshot

**Comment by opatiny** [comment]
> Are you sure it's `drawRectangle` ? This method can only draw straight rectangles and it is tilted in your screenshot

No, you are right, I was using `drawPolygon`, sorry.

**Comment by opatiny** [comment]
So I dug into the problem and it seems that the new implementation of line doesn't act as the previous one. Before, if we drew a line with the end of the line outside the image, only the "visible" part would be shown and the rest ignored. Not it looks like the line is looping over the image. I don't know if it is a bug in the `line` function.

Example of the current behaviour

```ts
 it.only('line out of image', () => {
    const image = testUtils.createGreyImage([
      [0, 0, 0, 0],
      [0, 0, 0, 0],
      [0, 0, 0, 0],
      [0, 0, 0, 0],
    ]);
    const from = { row: 0, column: 0 };
    const to = { row: 3, column: 8 };
    const result = image.drawLine(from, to, {
      strokeColor: [1],
      origin: { column: 0, row: 0 },
    });

    console.log({ result });
    expect(result).toMatchImageData([
      [1, 1, 0, 0],
      [0, 0, 1, 1],
      [0, 0, 0, 0],
      [0, 0, 0, 0],
    ]);
  });
```

The `console.log` returns
```bash
 {
      result: IJS {
        width: 4
        height: 4
        depth: 8
        colorModel: GREY
        channels: 1
        data: {
          [
           [  1   1   0   0]
           [  0   0   1   1]
           [  0   0   0  0]
           [  1   1   1   0]
          ]
        }
      }
    }
```

I don't really know how to fix this. Any advice @targos ?

**Comment by opatiny** [comment]
I think I will create a new method `setVisiblePixel` which sets a pixel iif it is inside the image. This should solve the issue.

**Comment by opatiny** [comment]
> I think I will create a new method `setVisiblePixel` which sets a pixel if it is inside the image. This should solve the issue.

I confirm that limiting the values before using `setValue` resolves the problem in my case. It is however not a very optimal solution (4 conditions to verify for each pixel).

Since the `line` method doesn't accept the images dimensions, it just "randomly" sets the pixels outside the image. We should remember this behaviour to avoid problems, but it is not a bug.
