### ISSUE TITLE
Implement `getFeretDiameters`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#138]
Migrate `feretDiameters` from `image-js`: https://github.com/image-js/image-js/blob/133897d8773265e4b709ed813ca8c0adea8f5ee0/src/image/roi/feretDiameters.js

**Comment by opatiny** [comment]
Description of the expected behaviour of the functions on this page: https://docs.c6h6.org/docs/eln/other_analysis/images/includes/rois/README

**Comment by lpatiny** [comment]
Indeed this is not correct.
max: Math.sqrt(2)
maxLine: [ [0,0], [1,1] ]
