### ISSUE TITLE
Implement functions to compare 2 images

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#152]
Implement the comparison algorithms between 2 images described in https://github.com/cheminfo/profid-padif/issues/20.
- `difference`
- `meanDifference`
- `dssim`
- `rmse`

**Comment by opatiny** [comment]
The `difference` algorithm is actually already implemented under the name `substract`.

**Comment by targos** [comment]
> The `difference` algorithm is actually already implemented under the name `substract`.

Then the name is wrong, please rename it to `subtract`.

**Comment by opatiny** [comment]
> > The `difference` algorithm is actually already implemented under the name `substract`.
> 
> Then the name is wrong, please rename it to `subtract`.

I'm not sure I got your point, since the algorithm already has the name `substract`. However do you have a better name for `meanDifference` so that it is coherent with `substract`?

**Comment by targos** [comment]
My point is the name `substract` is wrong (typo). It should be named `subtract`.

What exactly is the `meanDifference` ?

**Comment by opatiny** [comment]
> My point is the name `substract` is wrong (typo). It should be named `subtract`.
> 
> What exactly is the `meanDifference` ?

You're right sorry!

`meanDifference` is supposed to be the average of the subtraction between two images. It would be a number expressing how different two images are.

**Comment by targos** [comment]
> meanDifference is supposed to be the average of the subtraction between two images. It would be a number expressing how different two images are.

OK. We don't think it's really useful to implement exactly `meanDifference` so here's the suggestion:
- we already have `subtract`
- we add a `stats()` method that returns an object. For now it will contain only this (1 value per channel):
  `image.stats() // { sum: [4, 0, 850], mean: [1, 0 ,56] }`

When we need the mean difference, we can call both in the application

**Comment by opatiny** [comment]
Hi! I'm sorry but first computing the sum and then the difference is not equivalent to computing the differences and then taking the sum, as stated in the below example.
![photo_2022-10-11 08 28 15](https://user-images.githubusercontent.com/17711389/195012761-9184496a-d418-4c3c-ae2b-19544d204de0.jpeg)

**Comment by targos** [comment]
I never said we should compute the sum first.

**Comment by targos** [comment]
> Other question, should I use an existing library for SSIM, like this one : https://github.com/bytespider/ssim#readme, or should I reimplement it?
> 
> Wikipedia article: https://en.wikipedia.org/wiki/Structural_similarity

https://github.com/obartra/ssim Seems better

**Comment by opatiny** [comment]
I have a question concerning `rmse`, among others. I am not sure how to handle images with multiple channels. Should I compute a score for each channel independently or one for the whole image?

I thought this could also be a user option, so we could allow both behaviours.

**Comment by targos** [comment]
I'd check what is done in the literature / documentation of other libraries.

**Comment by opatiny** [comment]
In this post the two solutions don't use the same implementation to handle color images.... 
https://stackoverflow.com/questions/29973957/mse-for-two-vec3b-images-in-opencv

In the original code of PROFID, the RMSE is computed on the whole image, so that is how I reimplemented the method.
https://github.com/cheminfo/profid-padif/blob/e987695347ad241a267bacb31c1be9f08d9f6a2c/src/tools/digital_image_processing.py#L106-L120

**Comment by opatiny** [comment]
In the end:
- The comparison functions are applied on the `data` array directly and not on pixels.
- The `compute` functions return the values for each channel (so the stats are computed on each channel independently).
- The `stats` function was not implemented because it didn't allow a lot of optimisation.
