### ISSUE TITLE
Should we reimplement a feature matching algorithm?

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#156]
Understand how the ORB feature matching algorithm works and determine wether it's worth reimplementing. We need a function that would replace `align_images_fm()`, which is mentioned in https://github.com/cheminfo/profid-padif/issues/20.

Paper about ORB feature matching: https://iopscience.iop.org/article/10.1088/1742-6596/1237/3/032020/pdf

**Comment by opatiny** [comment]
Here is a little doc I wrote while documenting myself on feature matching. 

# Feature matching

## Definitions

- **Feature**: Distinct image patterns found in an image (blobs, corners, uniform intensity regions)
- **Descriptor**: array of numbers associated to a feature
- **Brute force (BF)**: all features of both images are compared. This is too slow to be used on real time images.
- **Inliers / Outliers**: Features that are matched correctly / incorrectly.
- **SIFT**: Scale-Invariant Feature Matching (independent from size and orientation) -> detect features in an image
- **BLOB**: Binary Large Object -> group of connected pixels with commom properties

## General concept

- **Detect** features in a source and destinations images
- **Extract** the features from the images
- Use a matcher to **compare** all the features found. Different algorithms can be used to compute the distance between two features. A commonly used one is **Hamming**.
- The three main steps are feature detection, description and matching.

## ORB feature detector

**ORB** is the acronym of Oriented FAST and Rotated BRIEF, where **FAST** stands for "Features from Accelerated Segment Test" (feature detection) and **BRIEF** stands for "Binary Robust Independent Elementary Features" (feature descriptors generation).

The Oriented FAST part means that you generate FAST features and then compute an orientation vector for each of them. The BRIEF algorithm allows to generate a binary vector, which is the descriptor of each feature. Use Gaussian blurring before BRIEF to remove noise effects. For each descriptor, a direction is computed as well, and the descriptors are rotated, in order to obtain rotation independence.

## References

- FM in Matlab: [https://www.youtube.com/watch?v=rbjybw9UyOg](https://www.youtube.com/watch?v=rbjybw9UyOg)
- FM in Python with cv2: [https://www.youtube.com/watch?v=Fe-KWKPk9Zc](https://www.youtube.com/watch?v=Fe-KWKPk9Zc)
- ORB: [https://iopscience.iop.org/article/10.1088/1742-6596/1237/3/032020/pdf](https://iopscience.iop.org/article/10.1088/1742-6596/1237/3/032020/pdf)
- Feature detection in JS -> is this interesting? [https://trackingjs.com/docs.html#introduction](https://trackingjs.com/docs.html#introduction)

**Comment by opatiny** [comment]
Now I've tried looking for an already existing library that would do some feature matching in JS and didn't found one.

Should I start implementing ORB feature matching from scratch on a new branch @targos ? It might be quite a chunk of code.

**Comment by targos** [comment]
> It might be quite a chunk of code.

How long do you think it may take to do it from scratch?

**Comment by opatiny** [comment]
> > It might be quite a chunk of code.
> 
> How long do you think it may take to do it from scratch?

It's difficult to estimate. Apparently they would be three main phases:
1) Feature detection : find the interesting areas in the image
2) Descriptors generation: create a vector that encrypts the feature
3) Feature matching: compare the features from source and target

Steps 1 and 2 appear to be the most difficult for now. I should be able to make it in around 6-8 working days

**Comment by opatiny** [comment]
I also found out that there is a JS implementation of OpenCV that has feature matching algorithm, would that be interesting?

https://scottsuhy.com/2021/02/01/image-alignment-feature-based-in-opencv-js-javascript/

**Comment by targos** [comment]
> Feature detection : find the interesting areas in the image

Can you try to propose an rough API for this phase? I'd like to know what kind of functions/options we can expose.

> I also found out that there is a JS implementation of OpenCV that has feature matching algorithm, would that be interesting?

It's interesting to play with OpenCV's API but the library is huge and we don't want to depend on it.

**Comment by opatiny** [comment]
> Can you try to propose an rough API for this phase? I'd like to know what kind of functions/options we can expose.
Yes, I'll do that now.

> It's interesting to play with OpenCV's API but the library is huge and we don't want to depend on it.
Yeah, that's what I expected.

**Comment by opatiny** [comment]
So from what I understood, the top level API would be just this:
```ts
export interface FindOrbKeypointsOptions {
  maxNbFeatures?: number;
  /**
   * Size factor for each scaling level.
   */
  scaleFactor?: number;
  /**
   * Number of scaling levels.
   */
  nbLevels?: number;
  /**
   * Level in which to put the original scale image features.
   */
  originalLevel?: number;
  /**
   * Specify the window radius for FAST.
   */
  windowRadius?: number;
  /**
   * Threshold for the FAST feature detection.
   */
  fastThreshold?: number;
  ...
}

export interface OrbKeypoint {
    origin: {row: number, column: number},
    /**
     * Angle in degrees
     */
    orientation: number;
}

export type OrbDescriptor = number[];

export function findOrbKeypoints(image: Image, options: FindOrbKeypointsOptions): OrbKeypoint[];

export function getOrbDescriptors(image: Image, keypoints: OrbKeypoint[], options: GetOrbDescriptorsOptions): OrbDescriptor[];
```

Then, once we have the `descriptors` for both image, we can compare them.

However, the functions `findOrbKeypoints` and `getOrbDescriptors` will use the FAST and BRIEF algorithms, which will produce a lot of sub-functions.

**Comment by targos** [comment]
OK, SGTM!

**Comment by targos** [comment]
Example from OpenCV we can use to compare with our implementation:
https://docs.opencv.org/5.x/dc/dc3/tutorial_py_matcher.html
https://github.com/opencv/opencv/blob/4.x/samples/data/box.png
https://github.com/opencv/opencv/blob/4.x/samples/data/box_in_scene.png
