### ISSUE TITLE
Implement FAST feature detection

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#159]
Original article: https://link.springer.com/content/pdf/10.1007/11744023_34.pdf

Goals:
- detect keypoints in an image using FAST algorithm
- sort the features using Harris filter

This is one of the featured discussed in #156.

**Comment by lpatiny** [comment]
Over 6000 citations, looks good !

![image](https://user-images.githubusercontent.com/1484241/199399357-93e22fce-2f3f-4097-bb64-8decff1b23b7.png)

In the jsDoc of the implementation please add the DOI link to this publication: https://doi.org/10.1007/11744023_34

**Comment by opatiny** [comment]
> In the jsDoc of the implementation please add the DOI link to this publication: https://doi.org/10.1007/11744023_34

It was already done ;)
