### ISSUE TITLE
level and min / max

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#166]
In level why the default values are 0 and maxValue rather than the current minValue and the current maxValue ?

https://github.com/image-js/image-js-typescript/blob/main/src/filters/level.ts#L59-L66

Currently it is difficult to increase the contrast because we need the current min and max.

If all the default values where current min / max we could write:

image.level({outputMin: 0, outputMax: image.maxValue}) to increase the contrast.

**Comment by opatiny** [comment]
It is possible that I mixed something up. I'll check it out next week.
