### ISSUE TITLE
Information about ROI

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#172]
In the previous code we had the following information about ROIs:

https://github.com/image-js/image-js/blob/17d7e83096318901d998d2139d974a2237af137c/src/image/roi/Roi.js#L745-L757

I see that currently there is getFerret at the level of Mask but I would expect also this feature to be available at the level of ROIs.

https://github.com/image-js/image-js-typescript/blob/7e8058ac1932f2e1c5230ee5051e9048f596c7cc/src/roi/Roi.ts#L9-L12

**Comment by opatiny** [comment]
This issue is related to https://github.com/image-js/image-js-typescript/issues/113, where we had decided to implement the functions on `Mask` instead of `Roi`, mainly to solve the issue that the MBR can be larger than the ROI.
