### ISSUE TITLE
Implement functions `getValueByPoint()` and `setValueByPoint()`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#180]
Currently, we have the `getValueByIndex` and `getValue` functions. However, we often manipulate `Point` objects, which makes the syntax not optimal. We have to do as follow:
```ts
const point = {column: 4, row: 2};

image.setValue(point.column, point.row, 0, 255);
```

Can I implement `getValueByPoint()` and `setValueByPoint()`? Or do you think it would over-complexify the API?
```ts
const point = {column: 4, row: 2};

const value = image.getValueByPoint(point, channel);
 image.setValueByPoint(point2, channel, value);
```

**Comment by targos** [comment]
Sure, you can implement it.
