### ISSUE TITLE
Reimplement markers (used to be shape)

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#186]
We should have the functionality to add markers on an image.

https://github.com/image-js/image-js/blob/e3ba8d4eabb214ce204bd386d92e3a3c9ec1199a/src/util/__tests__/shape.js

```
drawMarker(image, point, options);
drawMarkers(image, points, options);
```

- Should work on all images but binary images (using checkProcessable)
- default color: first channel to `maxValue` and alpha if available to `maxValue`

options:
- size: odd number >= 1
- shape: 'circle', 'triangle', 'cross', 'square' (default: cross)
- filled: true / false (default false)
- color: number[] 

If number of elements of `color` not equal to the number of components: throw. Please create in `validators` a function that check if color is compatible with current image.

Example:
```
drawMarkers(image, [{column: 1, row: 10}, {column:5, row:5}], {
  size: 5, filled: true, shape: 'triangle', color: [0,255,0],
})
```

**Comment by wadjih-bencheikh18** [comment]
I think it will better if we replace filled with fill which is the color the user want to fill the marker with
