### ISSUE TITLE
Transformation from source to matching keypoints

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#221]
Needed to align images.
[`cv2.estimateAffinePartial2D`](https://docs.opencv.org/4.7.0/d9/d0c/group__calib3d.html#gad767faff73e9cbd8b9d92b955b50062d)

**Comment by opatiny** [comment]
Linked post (but this doesn't handle outliers): https://stackoverflow.com/questions/17836996/computing-affine-transformation-from-2-sets-of-points

**Comment by opatiny** [comment]
Todo:
- [ ] Generalize the Levenberg-Maquard algorithm to work with multi-dimensional data: https://github.com/mljs/levenberg-marquardt
  - LM in matlab: https://ch.mathworks.com/matlabcentral/answers/446721-how-to-use-the-levenberg-marquardt-algorithm-to-fitting-data-and-get-the-first-derivative
  - In opencv:

**Comment by opatiny** [comment]
About LM generalisation: apparently  https://github.com/mljs/levenberg-marquardt is actually replacing  https://github.com/mljs/curve-fitting, which allowed multi-dimensional data. However they are nearly no examples in `curve-fitting` and the documentation is difficult to understand.

**Comment by opatiny** [comment]
We search the transformation to align the images in the end. Here is a good tutorial on the subject: https://learnopencv.com/image-alignment-feature-based-using-opencv-c-python/

**Comment by opatiny** [comment]
Trying to generalize `curve-fitting` to multiple dimension data: https://github.com/mljs/curve-fitting/issues/8

**Comment by opatiny** [comment]
Even if we have a lot of outliers, the ransac algorithm should handle them: 

> The RANSAC method can handle practically any ratio of outliers but need a threshold to distinguish inliers from outliers. The method LMeDS does not need any threshold but it works correctly only when there are more than 50% of inliers.

https://docs.opencv.org/4.7.0/d9/d0c/group__calib3d.html#gad767faff73e9cbd8b9d92b955b50062d

**Comment by opatiny** [comment]
In the end we developed a module to get the affine transformation from source to destination points specifically: https://github.com/mljs/affine-transform
