### ISSUE TITLE
Support fast and lossless rotations of multiples of 90°

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#225]
Currently, `image.rotate(90)`, goes through the complex transformation function. For multiples of 90°, it should be possible to have a fast implementation (maybe with a different name) that keeps all pixels and changes the image dimensions if it's not square.

**Comment by targos** [comment]
@stropitek any idea how we should call this method? I'm thinking about a function that only allows 3 possible values (clockwise rotation by 90, 180, and 270 degrees)

**Comment by targos** [comment]
Another option is to keep `rotate` for this use case, like opencv: https://docs.opencv.org/4.x/d2/de8/group__core__array.html#ga4ad01c0978b0ce64baa246811deeac24

And move the transformation-based rotation to a new method (name tbd).

**Comment by lpatiny** [comment]
I would keep only one function named `rotate`. It seems to me it is just an internal optimization if (angle % 90===0)

**Comment by targos** [comment]
It's not just an optimization. The behavior I want is different (rotation by 90/270 should change the dimensions of the returned image)

**Comment by stropitek** [comment]
In favor of renaming the transformation-based method to something else and use `rotate` for the new implementation.

I've thought of several possibilities including overloading the `transform` method, but I think the best would be to name it `transformRotate` to convey the fact that at the end it just calls `transform`

**Comment by stropitek** [comment]
Yes I also thought that if we have a good utility to create transforms, we don't even need the `transformRotate`. But having to compute the center of the image yourself makes it much less convenient.
