### ISSUE TITLE
setValue order of arguments

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#23]
I don't find it logical that we first ask for row and then for column and when creating the image we first use 'width' and then 'height'.

https://github.com/image-js/image-js-typescript/blob/main/src/IJS.ts#L259-L264

I'm always thinking as 'X' coordinates, 'Y' coordinates and I would invert the 2 first parameters to have

`setValue(column, row, ...)`

(same for getValue, setPixel and getPixel)

If seems logical that the first argument of setValue may take the same values that the first argument of the IJS constructor (so between 0 ... width-1).

@opatiny @targos What do you think ?

**Comment by targos** [comment]
We decided to use this order because it's the same as opencv and it follows the order of loops (first rows then columns)
