### ISSUE TITLE
Get list of grey algorithms

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#232]
I would need to make a loop to test all the grey algorithms but it seems I have only the type definition:

https://github.com/image-js/image-js-typescript/blob/c85e82d5c830c334ec0d9f8e4ecb91964f9f8944/src/operations/grey.ts#L5-L8

@targos  May I expose `greyAlgorithms` property that would `Object.keys(greyAlgorithms` ?

**Comment by lpatiny** [comment]
In fact Threshold algorithms are an enum so we can loop through it.

```
export enum ThresholdAlgorithm {
  HUANG = 'HUANG',
  INTERMODES = 'INTERMODES',
  ISODATA = 'ISODATA',
  LI = 'LI',
  MAX_ENTROPY = 'MAX_ENTROPY',
  MEAN = 'MEAN',
  MIN_ERROR = 'MIN_ERROR',
  MINIMUM = 'MINIMUM',
  MOMENTS = 'MOMENTS',
  OTSU = 'OTSU',
  PERCENTILE = 'PERCENTILE',
  RENYI_ENTROPY = 'RENYI_ENTROPY',
  SHANBHAG = 'SHANBHAG',
  TRIANGLE = 'TRIANGLE',
  YEN = 'YEN',
}
```

Could we do the same for GreyAlgorithms ?

But in this case should we put everything in camelCase ? (grey algorithms are in camelCase and mask uppercase)

**Comment by stropitek** [comment]
We usually have the convention that variables names (or property names if in an object) for constants are uppercase. The value itself does not have to be uppercase but it simplifies everything if key and value are the same.

Also we prefer using objects over enums:

```ts
export const ThresholdAlgorithm = {
  HUANG: 'HUANG',
  INTERMODES: 'INTERMODES',
} as const;

**Comment by targos** [comment]
> Also we prefer using const objects over enums

https://github.com/image-js/image-js-typescript/issues/140
