### ISSUE TITLE
Compute error between two images

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#235]
Implement a function that computes de difference between two images and returns the different as a value between 0 (perfect similarity) and 1 (completely different).

**Comment by targos** [comment]
> computes de difference between two images

This is the subtract method.

Unless there is standard documented way to convert the difference to a distance value, I think this shouldn't be a public method of the library. You can do that internally if needed.

**Comment by opatiny** [comment]
Subtract would return a map of all the difference, so it's not exactly what I wanted, however I can use `computeRmse` which would probably make more sense than what I intended to do.

In any case, I wouldn't have exposed the function.
