### ISSUE TITLE
Implement median filter for noise removal

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#239]
Removes noise without making edges blurry.

"Despeckle
This is a median filter. It replaces each pixel with the median value in its 3 x 3 neighborhood. This is a time consuming operation because, for each pixel in the selection, the nine pixels in the 3x3 neighborhood must be sorted and the center pixel replaced with the median value (the fifth). Median filters a good at removing salt and pepper noise." - https://imagej.nih.gov/ij/docs/menus/process.html

**Comment by lpatiny** [comment]
We can get inspired by:

https://github.com/image-js/image-js/blob/17d7e83096318901d998d2139d974a2237af137c/src/image/filter/medianFilter.js#L1-L64

The size could be an option.

**Comment by lpatiny** [comment]
What is important:
- deal with the border !
- check how 'mean' was implemented.
- median requires to create an array, use a typedArray ! The kind of typed array is related to the kind of image we have (8 or 16 bits depth).
- reuse always the same array
- use xMedian from ml-spectra.processing
