### ISSUE TITLE
Discussions about the 'Mask'

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#24]
Here is the result of the discussion that should be implemented

https://hackmd.io/@_iS0Gi_TQUqygrd9EH3-8g/r144ihxYF

@opatiny It should be divided in many issues and you may start to implement this.

**Comment by opatiny** [comment]
Functions to implement:
- [ ] `setBit`
- [ ] `getBit`
- [ ] `getBitByIndex`
- [ ] `setBitByIndex`
- [ ] `setValue`
- [ ] `getValue`
- [ ] `getValueByIndex`
- [ ] `setValueByIndex`
- [ ] `convertColor`
- [ ] `fill`
- [ ] `clone`
- [ ] `invert`

Mask specific functions:
- [ ] `erode`
- [ ] `dilate`
- [ ] `open`

To modify:
- [ ] `threshold` should return a `Mask`

**Comment by opatiny** [comment]
Should we implement all morphology functions of MatLab?
[https://ch.mathworks.com/help/images/morphological-filtering.html](https://ch.mathworks.com/help/images/morphological-filtering.html)

![image](https://user-images.githubusercontent.com/17711389/146516900-c7d25f09-7086-4b28-8959-71287b6df778.png)
