### ISSUE TITLE
New ROI property: ellipse

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#246]
I would like to have the information about the ellipse that fit the best a ROI.

We have something similar in PCA to create ellipses around points

https://github.com/cheminfo/jsgraph-sd-ellipse/blob/master/src/index.js

Still to discuss if we provide a parameter (nbSD). We would return an aspectRatio parameter I guess among other.

For return value we can use something very close to `Feret`

```js
    return {
      minorAxis: {
        length: 0,
        points: [
          { column: 0, row: 0 },
          { column: 0, row: 0 },
        ],
        angle: 0,
      },
      majorAxis: {
        length: 0,
        points: [
          { column: 0, row: 0 },
          { column: 0, row: 0 },
        ],
        angle: 0,
      },
      aspectRatio: 1,
    };
```

**Comment by lpatiny** [comment]
We should not have an option but the surface of the returned ellipsis should be the same as the ROI.

**Comment by lpatiny** [comment]
I forgot but we have already a code that does most of this:

https://cs.github.com/mljs/directional-distribution/blob/08ff0dd21db01a8aaad15173db341594b4a5e9a7/src/index.ts?q=ellipse#L13

You should add this library and use this code.

**Comment by targos** [comment]
Does it really make any mathematical sense to do this? The points of an ROI have no statistical relation between each other, without even talking about a normal distribution.
