### ISSUE TITLE
Aligning 2 set of points

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#248]
IF the 2 images have the SAME scale the operations are:

- identify key points (features)
- find the common features between the 2 images (ransac)
- align the centroids of the key points
- rotate

The 2 last processes can likely be done using ml-matrix using this approach:
- http://nghiaho.com/?page_id=671

**Comment by opatiny** [comment]
Retrieving angle from rotation matrix: take care to the orientation of the coordinate system.

" Non-standard orientation of the coordinate system

A rotation through angle θ with non-standard axes.
If a standard right-handed Cartesian coordinate system is used, with the x-axis to the right and the y-axis up, the rotation R(θ) is counterclockwise. If a left-handed Cartesian coordinate system is used, with x directed to the right but y directed down, R(θ) is clockwise. Such non-standard orientations are rarely used in mathematics but are common in 2D computer graphics, which often have the origin in the top left corner and the y-axis down the screen or page.[2]" - https://en.wikipedia.org/wiki/Rotation_matrix

**Comment by opatiny** [comment]
This was fixed in the `ml-affine-transform` module: https://github.com/mljs/affine-transform
