### ISSUE TITLE
Method to convert to canvas

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#25]
We will often need to convert the image to something that we can display in a canvas and need therefore the data as Uint8 RGBA array.

I think we should add a method like `toCanvas` ? That would ensure to have 8 bit depth and RGBA data.

So it would simply call convertColor and convertBitDepth

The same method could be available on a `Mask`

**Comment by targos** [comment]
It already exists because we can use writeCanvas

**Comment by lpatiny** [comment]
Ok so those lines https://github.com/image-js/image-js-typescript/blob/f41d0d3996af7ab5fde44264461e9e717b1c2032/demo/components/CameraTransform.tsx#L46-L48 are useless right ?

And we could ensure the conversion to 8 bits in `writeCanvas` right ?
