### ISSUE TITLE
Bug in feret diameter

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#258]
In some cases minimal Feret diameter is wrong

![image](https://user-images.githubusercontent.com/1484241/227792208-0e0c051e-9550-4f6e-b5f0-c35cd603c3e3.png)

**Comment by lpatiny** [comment]
There is a theorem that shows that the minimal feret diameter requires that one of the side of the hull curve is flat against the caliper.

**Comment by lpatiny** [comment]
The lengths of the diameters seem correct and it the the points of that is working as we can see in the minDiameter of this snapshot:

![image](https://user-images.githubusercontent.com/1484241/227794858-41ae1e7f-41b5-43f2-a9f8-44a10d279c19.png)

**Comment by opatiny** [comment]
Do we already have tools to do arrows / text annotations?

**Comment by lpatiny** [comment]
Well I decided to cheat a little bit and add a SVG layer hover the image. So I did a React component that allows to display the information about the ROI and we can generate any SVG code. It is 'just' a layer over the image so it will be easy to toggle on / off some of the annotation properties.

https://github.com/Hackuarium/screws-sorting/blob/44d493c94e143c21ded8b2d79d35fd56d577ed95/src/components/rois/RoiAnnotations.tsx#L34-L46

This is the result of the annotation showing Hull (red), Feret (black), MBR (blue) and ROI box (transparent red):

![image](https://user-images.githubusercontent.com/1484241/229517636-81e2184d-f071-4d70-9ab6-ad0d3defaa4b.png)

**Comment by lpatiny** [comment]
@EscapedGibbon Could you add a new property in minDiameter and maxDiamter: `lines`

https://github.com/image-js/image-js-typescript/blob/04f73e6f3f6cf700975760c34707aa07442f37c1/src/maskAnalysis/getFeret.ts#L126

```
lines: [ // those 2 lines are parallel
 [{x1,y1}, {x2,y2}], // the first line delimiting the calliper
 [{x3,y3}, {x4,y4}], // the second line delimiting the calliper
]
```

For the maxDiameter I'm pretty sure this line should be perpendicular of the maxDiamter. It should be just 'long enough' so that the full ROIs is included in the hypothetical rectangle that is described by the 2 lines.

![image](https://user-images.githubusercontent.com/1484241/229519527-2cd68845-a371-47ad-bdfa-94e56e122317.png)

For the minDiameter There is a theorem that proves that one of the hull side is along the calliper and we already calculate it when looking for the minDiameter. We should then 'only' find the 'from / to' of the lines to describe this virtual rectangle.
