### ISSUE TITLE
Code over complex ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#272]
Is it really necessary to use a call back to call a simple method ?

https://github.com/image-js/image-js-typescript/blob/04f73e6f3f6cf700975760c34707aa07442f37c1/src/roi/Roi.ts#L125-L129

https://github.com/image-js/image-js-typescript/blob/04f73e6f3f6cf700975760c34707aa07442f37c1/src/roi/Roi.ts#L331-L341

For me it makes the code very complex to read and to maintain (and also to contribute in fact).

**Comment by targos** [comment]
I agree. We should only use `#getComputed` when the computation has a big performance cost.

**Comment by stropitek** [comment]
TODO:
remove `#getComputed` from `ped` and `eqpc`
