### ISSUE TITLE
Add new method getRoiById on roiMapManager

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#279]
Currently we have the method getRois

https://github.com/image-js/image-js-typescript/blob/520994997f10b4bf56746cd63f1d8ef36ada3568/src/roi/getRois.ts#L39-L42

But if we know the id of the roi there is no simple method to retrieve it.

I would need a method 

roiMapManager.getRoiById( roiId ) that return a 'Roi' or throw an error if the Id is not known.

**Comment by targos** [comment]
How do you know the roi id in the first place? Can you give example code?
