### ISSUE TITLE
expose getMinMax in order to change image level ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#307]
I would like to get the min and max values for an image for each channel in order to increase the contrast.

So my current approach would be the following code but current `getMinMax` is not exposed.

```js
const {min, max} = getMinMax(image);
image = image.clone();
for (let i=0; i<image.components; i++) {
  image.level({inputMin: min[i], inputMax: max[i], channels: [i], out:image});
}
```

I also think that image.level could accept an array of min / max values or a number(for input and output) to achieve this functionality.

https://github.com/image-js/image-js-typescript/blob/30b0b08bf74cb2079a7ce3096c678d6217eba499/src/filters/level.ts#L20-L38

WDTY ?

**Comment by targos** [comment]
As a workaround, I would do `image.split()`, level each channel separately, then merge them back.
