### ISSUE TITLE
Improve custom inspection

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#31]
See current state in [snapshots](https://github.com/image-js/image-js-typescript/tree/main/src/__tests__/__snapshots__)

**Comment by opatiny** [comment]
Could I modify the symbol of IJS in order to print the images as rows and of pixels (e.g. rgbargbargba) so that we are consistent with the way we define images in the tests? I think this would help with debugging.

**Comment by targos** [comment]
yes, that's what I would expect
