### ISSUE TITLE
drawRectangle and border

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#311]
The parameters strokeColor and fillColor do not have the same type. `strokeColor` has a default value while `fillColor` is undefined. This allows to draw an empty rectangle without having to specify any parameter which may be practical.

However for consistency it could be better to have both undefined.

https://github.com/image-js/image-js-typescript/blob/383d96bfdb8e6b5fb2f0284002507951e81d1ffa/src/draw/drawRectangle.ts#L32-L40

I would also refactor this part

https://github.com/image-js/image-js-typescript/blob/383d96bfdb8e6b5fb2f0284002507951e81d1ffa/src/draw/drawRectangle.ts#L82-L123

To have

```
if (color) {
 ...
}

if (fill) {
 ...
}
```

In order to avoid duplicate code.

**Comment by opatiny** [comment]
Conclusions: also accept `none` for `fillColor` so that the types are coherent.

**Comment by lpatiny** [comment]
Here are the profiles.

![image](https://user-images.githubusercontent.com/1484241/233336371-f12571af-ea84-4ba8-8500-4e074b44c2d9.png)

![image](https://user-images.githubusercontent.com/1484241/233336424-b817ede4-303c-4bbc-b7e2-e5343a8db64b.png)

**Comment by opatiny** [comment]
> Here are the profiles.

Shouldn't this have rather been in your PR? https://github.com/image-js/image-js-typescript/pull/310
