### ISSUE TITLE
Delete round function ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#313]
If I understand well the only difference between Math.round and `round`

https://github.com/image-js/image-js-typescript/blob/70d251c3cd502172848bda1516575b09f7cb4318/src/utils/round.ts

Is that:
- Math.round(1.5) gives 2
- round(1.5) gives 1

This method is however quite time consuming

![image](https://user-images.githubusercontent.com/1484241/233338330-9fc84faa-3768-4285-a6dd-ef77dff2529d.png)

Could we just remove it ? Not sure those are edge cases or common cases.

Otherwise could we just replace it with:
`Math.round(value-1e-6)`

It will give the same result in 99.9999% of the cases I think

@targos WDYT ?

**Comment by targos** [comment]
We introduced the round function to have parity with OpenCV. I'd like to keep that. `Math.round(value-Number.EPSILON)` should be fine.

**Comment by lpatiny** [comment]
`Math.round(value-Number.EPSILON)` is not ok because we are quickly loosing enough significative digits if the number is larger than 1. This is why I came up with 1e-6.

```
Math.round(1.5 - Number.EPSILON)
1
Math.round(10.5 - Number.EPSILON)
11
```

```
Math.round(1.5-1e-6)
1
Math.round(10.5-1e-6)
10
Math.round(100000.5-1e-6)
100000
```

**Comment by lpatiny** [comment]
Interesting difference between clampedArray and typedArray

```
Uint8ClampedArray.from([-0.5,0.5,1.5,2.5,3.5,252.5,253.5,254.5,255.5])
-> Uint8ClampedArray(9) [
    0,   0,   2,   2, 4,
  252, 254, 254, 255
]
```

```
Uint8Array.from([-0.5,0.5,1.5,2.5,3.5,252.5,253.5,254.5,255.5])
-> Uint8Array(9) [
    0,   0,   1,   2, 3,
  252, 253, 254, 255
]
```

**Comment by targos** [comment]
> Apparently this is called Banker Rounding or Rounding half to even and this is what is used by openCV.

Ah, so our implementation is wrong wrt OpenCV?

**Comment by lpatiny** [comment]
The current implementation is exactly the same as Uint8ClampedArray (and I guess because Uint8ClampedArray is designed for images it is the same as OpenCV).

I did some quick benchmark

Only minMax, rounding by typedArray (floor): `typedArray`: 1.123s (not the same result)
MinMax + round from imageJS: `roundTypedArray`: 27.119s
`clampedArray`: 5.358s

New round algorithm: 10.721s

And the roundTypedArray gives exactly the same result as clampedArray (not the case of `typedArray`)

https://gist.github.com/lpatiny/a65bfbc457f3f1af15ca258ee22f25e1

Specs are defined here: https://tc39.es/ecma262/multipage/abstract-operations.html#sec-touint8clamp

So the new round is faster but using clamped array would still be a better approach
