### ISSUE TITLE
Cleanup comments in Roi.ts

### ISSUE THREAD

**Issue by stropitek** [image-js/image-js-typescript#316]
There are a lot of eslint warnings like this one

![CleanShot 2023-04-21 at 10 33 30](https://user-images.githubusercontent.com/4118690/233587587-053990a6-75db-4cbd-862b-04cf0886f446.png)

Please fix.

Remove comments which don't add any context or information like this one:

![CleanShot 2023-04-21 at 10 34 18](https://user-images.githubusercontent.com/4118690/233587803-4e3ff415-aa97-49c2-8210-6b6c7814cd23.png)

**Comment by targos** [comment]
We should not remove any comments but fix them with proper documentation.
