### ISSUE TITLE
New exports in ml-spectra-processing breaks TS

### ISSUE THREAD

**Issue by stropitek** [image-js/image-js-typescript#323]
Since v12.4.0 of the package is released, import statement in TS for this package are broken, see https://github.com/image-js/image-js-typescript/actions/runs/4893225405/jobs/8735938792

It's related to https://github.com/mljs/spectra-processing/commit/cb0025b8190e1fcb2a67a25b42d3438b3443e4dd

The error can be fixed if changing the module resolution strategy to `nodenext`, but introduces other issues with vite, forcing to `skipLibCheck`.

I don't feel comfortable with those ESM / CJS related issues, @targos do you understand why TS can't import the package?

**Comment by stropitek** [comment]
NB: for now I asked @EscapedGibbon to pin the version of this package to bypass the issue

**Comment by targos** [comment]
This should really have been published in a semver-major release...
IMO it's better to use `node16` instead of `nodenext` (less a moving target). For Vite, you should use `bundler`.

**Comment by stropitek** [comment]
> For Vite, you should use `bundler`

What is `bundler`?

**Comment by targos** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#--moduleresolution-bundler
