### ISSUE TITLE
Best way to output scaled version in canvas?

### ISSUE THREAD

**Issue by Xstoudi** [image-js/image-js-typescript#345]
`writeCanvas` use `context.putImageData` which is not considered as a draw function that can be influenced by something like `context.scale(x, y)`.

At first I tried resizing the image with `image.resize` but that's obviously very slow using it for interactive purpose.

Is there a way to use `drawImage` instead of `putImageData` to allow scaling directly on draw?

**Comment by lpatiny** [comment]
Why should we scale to a canvas ?

We can wrap the canvas in CSS to resize it.

![image](https://github.com/image-js/image-js-typescript/assets/1484241/6525648c-0b98-46d1-a682-e9c69e49b655)

This is done in the 'screw' project using the following library:

https://github.com/Hackuarium/screws-sorting/blob/main/package.json#L50
