### ISSUE TITLE
`drawPoints` does not handle points with floating point values

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#353]
I had to draw points for a test case and `drawPoints` was ignoring some of my points, which seemed like a very unexpected behaviour. I realised that some of the points were not whole values.

We should handle floating point values, either:
- throw an error and force user to pass integers
- round the points in the function before drawing them

@targos, wdyt?

**Comment by targos** [comment]
Let's `Math.round`, and do the same in other draw functions. I expect the result to be closer to what we would have with a continuous plan.

**Comment by opatiny** [comment]
> This is actually an issue in many functions, I've just had it in `copyTo`as well.

@targos, in the case of `copyTo` we said that we would like to throw and not round right?

**Comment by targos** [comment]
Yes

![image](https://github.com/image-js/image-js-typescript/assets/2352663/761a4dbf-7394-42b0-b10f-5429acab54d1)
