### ISSUE TITLE
Align source and reference image using feature matching

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#361]

**Comment by opatiny** [comment]
I have made test with some real-life images and the script start to work on some of them.

![Image](https://github.com/image-js/image-js-typescript/assets/17711389/08c2e82f-c2fc-4162-8483-549cc5b519c7)


![Image](https://github.com/image-js/image-js-typescript/assets/17711389/9bbe3d88-5dfe-4bb0-b951-b324dd0fd9d2)

Transform found:
```
{
  transform: {
    rotation: -0.19385536506284526,
    scale: 1.0368736678504342,
    translation: { column: 42, row: 8 }
  },
  nbMatches: 49,
  nbInliers: 5,
  nbRansacIterations: 1000
}
```


Another image, that is pretty different from the source works a lot worse. Maybe we could still enhance the matching a bit, but I think the matching is bad because the typo is different.


![Image](https://github.com/image-js/image-js-typescript/assets/17711389/01c3889c-bc28-478b-b81b-d916c72502cc)

Transform found:
```
{
  transform: {
    rotation: 179.74815204172754,
    scale: 10.581497571701478,
    translation: { column: 1629, row: 1215 }
  },
  nbMatches: 25,
  nbInliers: 2,
  nbRansacIterations: 1000
}
```

This result doesn't make sense. We can see that if they are only 2 inliers, the results are probably aberrant.

**Comment by opatiny** [comment]
I created a new function called `filterDistanceEucledean`, which takes matches where many source keypoints can point to the same destination keypoint, and which returns the keypoints that are the closest in space to the ones in the destination. It is a simple way to eliminate some outliers in our specific case where we approximately know where the destination is.

By using this function, I am getting better results with the image with a different typo, even though they are still varying from one run to another. Here is the result in a good case.

![Image](https://github.com/image-js/image-js-typescript/assets/17711389/ed08aaa5-0aaa-4862-b4e2-4bb81e146703)



![Image](https://github.com/image-js/image-js-typescript/assets/17711389/70d94013-27f9-4787-9dfe-039add004c6b)

**Comment by opatiny** [comment]
Todo:
- [ ] The image that is extended with a margin should be the source and not the reference.
- [ ] Test an ROI containing some background

**Comment by opatiny** [comment]
# Test on an ROI containing background

## Images with enhanced contrast
![source](https://github.com/image-js/image-js-typescript/assets/17711389/75a2b0cc-4904-4a99-bb4e-c45ed934cae0)

Reference:
![destination](https://github.com/image-js/image-js-typescript/assets/17711389/0aa26503-0c04-4e90-9cc4-78fd4d64b450)

## Keypoints found and matches
![debug1_roi2](https://github.com/image-js/image-js-typescript/assets/17711389/fba1cfe7-e641-4629-abc0-368a83f0038e)

## Final transform found:
```
{
  transform: {
    rotation: -176.93926671318394,
    scale: 0.7716111373412708,
    translation: { column: 359, row: 153 }
  },
  stats: {
    nbMatches: 106,
    nbInliers: 3,
    nbRansacIterations: 1000,
    nbSourceKeypoints: 239,
    nbDestinationKeypoints: 280
  }
}
```
As they are a lot of keypoints, it is more likely that the model found by ransac has more inliers, here 3 instead of the usual 2 when the model is bad. To detect bad matching, we could use a criteria `nbInliers/nbKeypoints` that should have a minimal value, as well as requiring a minimum of 3 inliers.

**Comment by targos** [comment]
`rotation: -176.93926671318394,`

This transformation would be rejected. We know the orientation is already the same. You can see in the current Python code that there are some checks done on the feature matching alignment. If it cannot be done it falls back to another method (minimum difference).
I doesn't make sense to try and find matching keypoints when the images have different visual patterns.

**Comment by opatiny** [comment]
> I doesn't make sense to try and find matching keypoints when the images have different visual patterns.

I totally agree, but we have to compute the matches in order to get the transformation and we can then check the rotation and scale rignt?
