### ISSUE TITLE
`channels` should be renamed `components`

### ISSUE THREAD

**Issue by Xstoudi** [image-js/image-js-typescript#370]
The `channels` parameter allow passing alpha, it should probably be named `components`.
https://github.com/image-js/image-js-typescript/blob/ce6a4f4a28f61f5968df56db69cceed887866fbb/src/filters/level.ts#L13

**Comment by targos** [comment]
If it allows passing alpha, `channels` is the right name.
An RGBA image has 4 channels, 3 components.
