### ISSUE TITLE
Problem with validate channel ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#371]
Is validateChannel correct ?

`channel > image.channels`

If we want to validate a channel I think it should be `channel >= image.channels`

https://github.com/image-js/image-js-typescript/blob/ce6a4f4a28f61f5968df56db69cceed887866fbb/src/utils/validators.ts#L20-L29

WDYT ?

**Comment by targos** [comment]
Seems a bug.

**Comment by lpatiny** [comment]
There may be some more confusion between `component` and `channel` in various function. We call the option `channel` but nevertherless we allow alpha component like in 

https://github.com/image-js/image-js-typescript/blob/ce6a4f4a28f61f5968df56db69cceed887866fbb/src/filters/level.ts#L12C1-L13C23

as pointed by @Xstoudi

**Comment by targos** [comment]
Alpha is a channel

**Comment by targos** [comment]
https://github.com/image-js/image-js-typescript/blob/794486e4b901b8df7f79e140a96c871cd50fdfcb/src/Image.ts#L188-L197
