### ISSUE TITLE
computeThreshold is inconsistent

### ISSUE THREAD

**Issue by EscapedGibbon** [image-js/image-js-typescript#385]
computeThreshold function does not calculate a threshold index (which then can be multiplied by maxValue) but gives a threshold value instead

**Comment by opatiny** [comment]
The issue was solved in the following commit:  [8ca381f](https://github.com/image-js/image-js-typescript/commit/8ca381fd1d3f723682375bf77dc9e163eeb2eee6)

Related issue: #374
