### ISSUE TITLE
Mask optimization

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#39]
Currently we are converting in a clean way a boolean to a number using the method `boolToNumber`:

https://github.com/image-js/image-js-typescript/blob/d181906c1359157b2e87beb10b86ebf71929a125/src/Mask.ts#L185-L189

However javascript would allow to write directly (in which value is a number of boolean):

```
   const index = row * this.width + column; 
   this.data[index] = value && 1; 
```

but typescript would not be very happy.

The time difference is not negligible. In a small test the current approach is 40% slower than using the second approach. I think we should focus on speed in this library and add some ts-expect-error if needed.

**Comment by targos** [comment]
If it works with `&& 1`, I'm pretty sure it should work directly with `value` too.

**Comment by targos** [comment]
Can you also try to convert using a bitwise operation? Like `this.data[index] = value | 0`

**Comment by lpatiny** [comment]
At the speed point of view `value | 0` has no impact (as fast as just `value` but typescript is still not happy

![image](https://user-images.githubusercontent.com/1484241/150755084-33ed9e2d-a0da-44ca-a51f-7b6f8a1f7cab.png)

Sorry I was wrong with `this.data[index] = value && 1;` I just was meaning `this.data[index] = value;` and in both cases typescript is not happy.

Would this be a solution ? Does not seem shocking to me.

```
    const index = row * this.width + column;
    this.data[index] = value as number;
``` 

And it allows to remove the method `boolToNumber`
