### ISSUE TITLE
Regions of Interests (ROI)

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#40]
MD file for discussion tomorrow

https://hackmd.io/lRJJwRiERH6c1IlSsuC38w

**Comment by targos** [comment]
maybe something interesting can come from https://plantcv.readthedocs.io/en/v3.0.5/multi-plant_tutorial/

**Comment by opatiny** [comment]
Linked issues:
- #60

**Comment by opatiny** [comment]
> maybe something interesting can come from https://plantcv.readthedocs.io/en/v3.0.5/multi-plant_tutorial/

There is something that might be worth implementing, which is to be able to run some of the methods in another color space. For example, they use the green-magenta channel of the LAB space to detect plants.

![image](https://user-images.githubusercontent.com/17711389/174731245-8cb41ec2-8413-4272-9f05-520f3cfeef57.png)
