### ISSUE TITLE
Migrate `cannyEdge()`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#43]
Migrate `cannyEdge()` from `image-js`.

[`cannyEdge.js`](https://github.com/image-js/image-js/blob/5811f5b7e7677cdda1d8ac124a5c963812e5cd59/src/image/operator/cannyEdge.js)

This function seems to be similar to the matlab `bwperim()` function: [https://nl.mathworks.com/help/images/ref/bwperim.html](https://nl.mathworks.com/help/images/ref/bwperim.html)

**Comment by targos** [comment]
See the comments in https://github.com/image-js/canny-edge-detector/issues/2

It seems that there is an issue with our implementation.

**Comment by opatiny** [comment]
The function required `hypotenuse()`, which was migrated from: [https://github.com/image-js/image-js/blob/legacy/src/image/filter/hypotenuse.js](https://github.com/image-js/image-js/blob/legacy/src/image/filter/hypotenuse.js)

**Comment by opatiny** [comment]
Todo: write the function test.

**Comment by opatiny** [comment]
This page explains how the canny edge implementation works: https://justin-liang.com/tutorials/canny/#:~:text=Non%20maximum%20suppression%20works%20by,the%20gradient%20direction%20of%20q.

**Comment by opatiny** [comment]
> See the comments in [image-js/canny-edge-detector#2](https://github.com/image-js/canny-edge-detector/issues/2)
> 
> It seems that there is an issue with our implementation.

I indeed modified the modulo value of [line 93](https://github.com/image-js/image-js-typescript/blob/fad32e75be3e7bbdff0d54ee31ab41f66ccce6aa/src/morphology/cannyEdgeDetector.ts#L84-L94), which removed the thick edges problem. However, now the edges are nearly too thin and not very clear. I'll see what other changes could enhance that.


```typescript
for (let row = 1; row < height - 1; row++) {
      let direction =
        (Math.round(
          Math.atan2(
            gradientY[getIndex(row, column, 0, image)],
            gradientX[getIndex(row, column, 0, image)],
          ) *
            (4 / Math.PI),
        ) +
          4) %
        4;
```

**Comment by opatiny** [comment]
Interesting tool to compare with our results: [http://bigwww.epfl.ch/demo/ip/demos/edgeDetector/](http://bigwww.epfl.ch/demo/ip/demos/edgeDetector/)
