### ISSUE TITLE
Exporting 16-bits images as png doesn't work 

### ISSUE THREAD

**Issue by moonayyur** [image-js/image-js-typescript#444]
In the function `encodePng` that uses `fast-png` library : 
```
encode(image.getRawImage(), options);
```
We have :
```
Image.getRawImage(): {
    width: number;
    height: number;
    data: ImageDataArray;
    channels: number;
    bitDepth: BitDepth;
}
```

While : 
```
export interface ImageData {
    width: number;
    height: number;
    data: PngDataArray;
    depth?: BitDepth;
    channels?: number;
}
```

`bitDepth` in `getRawImage` has to be changed to `depth`
So here since we don't pass a value to `depth` it uses the default value in `fast-png` which is 8 bits

**Comment by stropitek** [comment]
Probably introduced by https://github.com/image-js/image-js-typescript/pull/298

Can you make a PR with a fix?

**Comment by moonayyur** [comment]
@stropitek was there a reason why `bitDepth` was choosen over `depth` to start with ?

**Comment by stropitek** [comment]
Maybe better to ask @targos since he worked on it but I think it was just for clarity. `depth` does not specify the unit so it could as well could have been expressed in bytes, not bits.

**Comment by targos** [comment]
There were three different names for the same thing (depth, bit depth, color depth) and we had to choose one for consistency.
