### ISSUE TITLE
Missing features from ImageJS

### ISSUE THREAD

**Issue by EscapedGibbon** [image-js/image-js-typescript#456]
So far this is what we came up with Daniel.
Missing features:
- [x] pad (adds padding to the image -> TODO, but maybe with border interpolation options like in typescript)
- [x] bmp encoding (TODO)
- [x] multiply/divide (functions that multiply/divide each pixel by a certain value-> TODO, seems easy to implement)
 - [ ] mergeRoi, mergeRois (merge several regions of interest into one -> talk to Luc)
- [ ] getClosestCommontParent (finds common parent between two masks)(talk to Luc)
- [ ] getRelativePosition()(talk to Luc)
- countAlphaPixels (counts all the transparent pixels -> not TODO, there doesn't seem to be a need for such function.)
- cmyk,hsl,hsv color models(not TODO)
- paintLabels (Last time we discussed it it was probably decided not to implement it in the end-> NOT TODO)
- abs (makes all the values in the image data absolute-> not TODO. Typescript library uses `uint` arrays for storing data, so they cannot be negative.)

**Comment by lpatiny** [comment]
The 3 missing features should be implemented once we have a real application and a real problem (if needed).
