### ISSUE TITLE
Multiple image analysis

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#467]
We have a sequence of images stored as a TIFF and would like to:
- make an average
- caclulate ROI on the average
- extract the average value of ROI on all the images

I'm wondering if this can be achieved using image-js-typescript.

**Comment by EscapedGibbon** [comment]
This is too specific for a public API, with too many hidden things happening inside.

We will create a tutorial on how to extract the average value of ROI on all the images.
