### ISSUE TITLE
`separableConvolution()` has unexpected behaviour

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#47]
In the following test, we would expect the sum of the resulting image to be 255, but we get 313.

https://github.com/image-js/image-js-typescript/blob/23d184902801a1d2d79fde3b235e9b759b078ac0/src/filters/__tests__/gaussianBlur.test.ts#L5-L26

![image](https://user-images.githubusercontent.com/17711389/155690127-2cd97257-280d-4ccb-8880-5ff07d44dd21.png)

**Comment by targos** [comment]
Reference on separable filter: https://en.wikipedia.org/wiki/Separable_filter

**Comment by opatiny** [comment]
Actually the testcase was wrong.

Here is a code used in matlab to verify that the expected behavious was correct.

```m
%% Testing matlab gaussian blur
clc; clear; close all;

%% Image

image = [ 0 0 0 0 0
          0 0 0 0 0
          0 0 255 0 0
          0 0 0 0 0
          0 0 0 0 0];
      
%% Blurring
blurred = imgaussfilt(image,1,'FilterSize',5)

%% Sum
result = sum(blurred, 'all')
```

![image](https://user-images.githubusercontent.com/17711389/155700791-cc61aecf-840c-45b6-9632-599f91457787.png)
