### ISSUE TITLE
Use `setBlendedPixel` in draw* methods

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#477]

**Comment by EscapedGibbon** [comment]
I have a question regarding the way to fix it. Currently draw* functions use setVisiblePixel to modify values and they modify them only if the pixel is in bounds of the image. setBlendedPixel doesn't do that. So by changing the function the draw* function's behavior will change as well. Therefore my question is how to modify in a more correct way? Should I change `setValue`  which is used in `setBlendedPixel`? Or should I add a check in functions themselves?
Also after I made the former modification (added check to `setValue`), I stumbled on the test below that doesn't pass and I wonder if such an implementation is fine.

https://github.com/image-js/image-js-typescript/blob/ec04a5773c308eb5730b95007270e3dead632994/src/__tests__/Image.test.ts#L151-L157

There is no error but the point coordinates modified in the test will actually be `{row:1, column:5}`, right?

**Comment by stropitek** [comment]
I haven't fully understood what you changed.

Maybe before explaining how you are going to change the code, can you explain what `setBlendedPixel` was doing differently than `setVisiblePixel`, and what you think is the correct behaviour. My understanding from your explanation is just that calling `setVisiblePixel` on an out of bound pixel is a noop, but not when calling `setBlendedPixel`.

**Comment by EscapedGibbon** [comment]
Yes. And I am not sure if it's okay to call `setBlendedPixel` and have the possibility to modify the value that was not intended to be modified.
