### ISSUE TITLE
Change Mask to use 0 and 255 instead of 0 and 1

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#48]
Modify the `setBit()` function to have instead `setBitOn()` and `setBitOff()`. `setBitOn()` should set to 255 and `setBitOff()` to 0.

**Comment by opatiny** [comment]
After discussion, the `setBit()` function should be kept! However, `setBitOn()` and setBitOff()` can be added to the API.

**Comment by opatiny** [comment]
When implementing this, a few issues popped up:
- what should be the acceptable values the user can pass? should it still be 0 and 1 or should it be 0 and 255?
- how should the tests work? should we modify `toMatchMask()` so that it internally converts the ones to 255 or should the tests use 255 directly? visually, it's better to keep 1 and 0 because the formatting is better
- what should `getValue()` return? 1 or 255?

**Comment by targos** [comment]
* user can pass a boolean or any number. false and 0 -> 0, otherwise -> 255

> should we modify toMatchMask() so that it internally converts the ones to 255 

yes

> what should getValue() return? 1 or 255?

users should not use it as a value but as a bool

**Comment by opatiny** [comment]
Is this issue still relevant?

**Comment by targos** [comment]
I guess not.
