### ISSUE TITLE
Replace `Math.max()` and `Math.min()` by ternary operators

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#49]
Replace all occurrences of `Math.max()` and `Math.min()` by ternary operators when they are used inside of loops and to compare only two values. We do this to optimise speed.

**Comment by targos** [comment]
Do you have proof it is faster?

**Comment by lpatiny** [comment]
Yes the difference is surprisingly big and @targos we had once a look at the generated bytecode. You can actually win a factor 4 in some cases:

https://jsbench.me/d5l0dh502g/1

For algorithms like https://github.com/image-js/image-js-typescript/blob/5c3340366c3efbf2e0062259857086f37efebe6a/src/morphology/dilate.ts#L151-L153 in which the comparison is in a loop of a loop of a loop I would expect we win a factor 2 but maybe @opatiny could try with a real image.

**Comment by lpatiny** [comment]
Seems that the difference between a M1 processor and Intel processor is huge and does not make sense. M1 generally likes Math.min especially in Safari on typed array.

`Abs` would be the best compromise for now but it looks terrible and hopefully the javascript engine will improve even on Intel processor ;) So better to wait and see (and keep Math.min).

https://jsbench.me/d5l0dh502g

Bigger numbers are better. Number of operations per seconds.

| Processor      | M1     | M1      | M1     | Intel  | Intel   | Intel  |
| -------------- | ------ | ------- | ------ | ------ | ------- | ------ |
| Browser        | Chrome | Firefox | Safari | Chrome | Firefox | Safari |
| Math.min       | 9939   | 8858    | 2101   | 2212   | 3809    | 4244   |
| Ternary        | 2482   | 2158    | 2189   | 2404   | 1562    | 1556   |
| Abs            | 9477   | 7762    | 9610   | 6593   | 4167    | 4354   |
| Math.min typed | 9881   | 9858    | 27458  | 2063   | 4568    | 4877   |
| Ternary typed  | 2283   | 2240    | 26668  | 2189   | 1659    | 1855   |
| Abs typed      | 7301   | 8626    | 7709   | 4276   | 4343    | 4465   |

Please note that M1 and Intel are obviously not the same machine so only relative numbers between implementations should be compared.
