### ISSUE TITLE
Migrate `flipX()` and `flipY()` from `image-js`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#56]
These two functions seem pretty easy and could be migrated quickly. 

https://github.com/image-js/image-js/blob/8bfbcc524daafc35c35df62f5d18e7679deae7ee/src/image/filter/flipX.js

**Comment by lpatiny** [comment]
We could implement

`flip(options={})`

options:
- axis: 'horizontal' (default) | 'vertical' | 'both'
- out
