### ISSUE TITLE
Implement `getBorderPoints()`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#78]
The idea is to find all the pixels that are on the border of the roi (in contact with other rois). We should have an option to have only the points outside or also the points touching rois inside the current roi.

- We create an **array with the coordinates** of the pixels that are on the border. This will be useful for the MBR.
- We should see if it's possible to use `clearBorder` to achieve that.
- It's an internal method.
- Whether corners are considered as a connection is an option.

```ts
[
  [ 4, 2 ], [5, 6], ... // array of points: [column, row]
]
```

**Comment by opatiny** [comment]
The reference point for the coordinates should be the top-left corner of the ROI mask.

**Comment by opatiny** [comment]
This will be the new function replacing `roi.contourMask()`: https://github.com/image-js/image-js/blob/b3b7499a5b0e6ee93f69e0646115653b3c044687/src/image/roi/Roi.js#L271-L315

**Comment by lpatiny** [comment]
Don't know if it exists but would be nice to have a `paintPoints`, sorry a `drawPoints` method as well to be able to debug (and probably other applications as well).
