### ISSUE TITLE
draw various shapes

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#79]
We may want to be able to annotate manually images but also to display the result of automatic analysis.

This may include polygon, polyline, rectangle, circle, ellipse and text (in the future).

Paint will only be available on 8 or 16 bits images (IJS type) and not on Mask (1 bit images).

Example of code:

```
const ijs = new IJS(500, 500);

ijs.paintLine(from:{row, column}, to:{row, column}, options={color});
// example: ijs.paintLine( {row: 5, column: 5}, {row: 10, column: 10}, {color: [255,0,0,255]})
ijs.paintRectangle({row, column, width, height}, options={color, fill}); // color = border color, fill = fill color
ijs.paintPolygon({column, row}[], options);
ijs.paintPolyline({column, row}[], options);
```

`color` and `fill` should be an array of number or a number.

If it is a number all the components (meaning all the channels but alpha) would be changed and alpha would be set to MAX_VALUE (image 8 bits it is 255, image 16 bits it is 65535).

If it is an array, the array length have to be the number of channels (nbComponent + alpha) ! If the array.length != image.channels => throw an error

There is some code that we did and need to be adapted: https://github.com/image-js/image-js/tree/legacy/src/image/operator

**Comment by wadjih-bencheikh18** [comment]
@lpatiny 

- [x] line 
- [x] polyline
- [x] polygone
- [x] circle
- [x] rectangle

any missing shape?

**Comment by lpatiny** [comment]
Those are enough for me.
