### ISSUE TITLE
operations/convertToGrey

### ISSUE THREAD

**Issue by lpatiny** [image-js/image-js-typescript#8]
Is it ok to add a new method 'convertToGrey' that allows all the existing algorithms ?

I would also like to write as code:

`let greyImage = colorImage.grey({algorithm: 'minimum');`

https://github.com/image-js/image-js/blob/legacy/src/image/transform/grey.js

https://github.com/image-js/image-js/blob/legacy/src/image/transform/greyAlgorithms.js

**Comment by targos** [comment]
That said, I think that for simplicity, `image.grey()` should be only applicable to RGB and RGBA images.

For generic color conversions in all directions, we keep `image.convertColor(newColorModel)`

**Comment by opatiny** [comment]
Things left to do: make the grey test work and check they are no more bugs.
