### ISSUE TITLE
row column must be always in the same order in functions

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [image-js/image-js-typescript#81]
- `const out = new IJS(2, 3);` row is the second param (height)
- `image.setValue();` row is the first param

**Comment by targos** [comment]
Are there other function than `setRow/getRow` and `setPixel/getPixel` which have row as the first param?

**Comment by wadjih-bencheikh18** [comment]
i think it's better to have height as the first param in the constructor

**Comment by targos** [comment]
I'm not sure about that. In possible all other software, image dimensions are referenced in the opposite order (width, height).

**Comment by opatiny** [comment]
We will change the implementation in order to call the parameters in the order `column`, `row`. This will also make the API more similar to the old `image-js`.
