### ISSUE TITLE
Paint or draw?

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#87]
Just a naming question.

**Comment by targos** [comment]
@wadjih-bencheikh18, @stropitek  what do you think? The question is whether we should call the methods `paintLine` or `drawLine`. Intuitively I think about draw, but Luc paint 😄

**Comment by wadjih-bencheikh18** [comment]
I prefer paint

**Comment by stropitek** [comment]
Would go for draw. It's semantically closer to what is actually happening. That is the language which seems to be used if you look at the web canvas mdn documentation. It's also the language used for the the android canvas API. https://developer.android.com/reference/android/graphics/Canvas

I associate paint with the paint bucket tool in photoshop which allows to fill an area with a color.

**Comment by opatiny** [comment]
I'd rather go with draw too

**Comment by targos** [comment]
Let's go with draw!
