### ISSUE TITLE
Blend transparent pixels in drawing methods

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#88]
New internal functions: `getBlendedAlpha` `getBlendedComponent`

This is how we computed the new color when there is an alpha in the `copyTo` method:
https://github.com/image-js/image-js-typescript/blob/71046a17e80bf4b15526ea31eb27f13c44b8632a/src/operations/copyTo.ts#L61-L78

**Comment by opatiny** [comment]
Instead of the two proposed functions, we'll directly create a function on an image that takes the coordinates and the pixel to blend: `setBlendedPixel()`. If the pixel has no alpha, or if the alpha is maximal, it is equivalent to `setPixel()`.
