### ISSUE TITLE
Implement `paintMask()`

### ISSUE THREAD

**Issue by opatiny** [image-js/image-js-typescript#95]
Create a function that allows to colour all the pixels of a mask in a given image.

Parameters:
- mask
- column, row (default 0,0)
- a color (default black)

This issue depends on #88

**Comment by lpatiny** [comment]
Should it be paintMask or drawMask ?

**Comment by stropitek** [comment]
I think "paint" makes more sense here as the operation is "filling with a color"

**Comment by opatiny** [comment]
We want the following behaviour for this function:
- we have a boolean option `blend` which specifies wether the given colour should be blended with the original pixel or not.
- if `blend` is `false`, the user can modify only some of the channels by doing the syntax `[undefined, 50, undefined, 255]`. This would for example set the green channel to 50 and the alpha channel to 255, while not modifying the other channels.

**Comment by targos** [comment]
> if blend is false, the user can modify only some of the channels by using the syntax [undefined, 50, undefined, 255]. This would for example set the green channel to 50 and the alpha channel to 255, while not modifying the other channels.

What's the use case for that?

**Comment by opatiny** [comment]
For instance, I wanted to make a demo where the background image is faded / translucent and the ROI that is interesting is opaque. We could acheive that by using `blend = false` and `color = [undefined, undefined, undefined, 255]`.

**Comment by targos** [comment]
Ok, can you also (or only) accept `null` for slots to ignore? I don't like using `undefined` as a value.

**Comment by opatiny** [comment]
Yes, ofc. Is `null` considered as a number? I don't know how to handle the overloads for the function, because I should accept `null` values only if `blend` is false.

**Comment by targos** [comment]
No, null is not a number. You can use `null` as a type (for example `Array<number | null>`)
